services:
  # 1. Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: payment_gateway_db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_gateway_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - payment-network

  # 3. Frontend React (Vite + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payment_gateway_frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - payment-network

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge